# Generated by Django 3.0.5 on 2022-11-18 18:11

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_picture', models.URLField()),
                ('wine_id', models.IntegerField(default=0)),
                ('kname', models.CharField(max_length=100, verbose_name='와인명')),
                ('ename', models.CharField(max_length=100, verbose_name='winename')),
                ('winetype', models.CharField(max_length=10, verbose_name='winetype')),
                ('kr_country', models.CharField(max_length=50, verbose_name='국가명')),
                ('kr_region', models.CharField(max_length=50, verbose_name='지역명')),
                ('kr_grape_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('sweet', models.IntegerField(verbose_name='당도')),
                ('acidic', models.IntegerField(verbose_name='산도')),
                ('body', models.IntegerField(verbose_name='바디감')),
                ('tannic', models.IntegerField(verbose_name='타닌감')),
                ('notes_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('food_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('have_tried', models.BooleanField(default=False, verbose_name='먹어본 와인')),
                ('is_liked', models.BooleanField(default=False, verbose_name='찜한 와인')),
            ],
        ),
        migrations.CreateModel(
            name='WineCeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winesellers', to=settings.AUTH_USER_MODEL)),
                ('wine', models.ManyToManyField(related_name='winesellers', to='wineceller.Wine')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
