# Generated by Django 4.1.3 on 2022-11-25 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wineceller", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wineceller",
            name="wine",
        ),
        migrations.AddField(
            model_name="wineceller",
            name="wine_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wine",
            name="wine_id",
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name="wineceller",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winecellers",
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
