# Generated by Django 4.1.3 on 2022-11-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wineceller", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("wine_picture", models.ImageField(upload_to="")),
                ("kname", models.CharField(max_length=100, verbose_name="와인명")),
                ("ename", models.CharField(max_length=100, verbose_name="winename")),
                ("winetype", models.CharField(max_length=10, verbose_name="winetype")),
                ("country", models.CharField(max_length=50, verbose_name="국가명")),
                ("region", models.CharField(max_length=50, verbose_name="지역명")),
                ("grape_list", models.CharField(max_length=50, verbose_name="품종리스트")),
                (
                    "sweet",
                    models.PositiveIntegerField(max_length=50, verbose_name="당도"),
                ),
                (
                    "acidic",
                    models.PositiveIntegerField(max_length=50, verbose_name="산도"),
                ),
                (
                    "body",
                    models.PositiveIntegerField(max_length=50, verbose_name="바디감"),
                ),
                (
                    "tannic",
                    models.PositiveIntegerField(max_length=50, verbose_name="타닌감"),
                ),
                ("notes_list", models.CharField(max_length=50, verbose_name="향 리스트")),
                (
                    "food_list",
                    models.CharField(max_length=50, verbose_name="푸드 페어링 리스트"),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AlterField(
            model_name="wineceller",
            name="wine",
            field=models.ManyToManyField(
                related_name="winesellers", to="wineceller.wine"
            ),
        ),
    ]
