# Generated by Django 4.1.3 on 2022-11-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wineceller", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="wineceller",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
