# Generated by Django 4.1.3 on 2022-11-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wineceller", "0002_wine_alter_wineceller_wine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine", name="wine_picture", field=models.URLField(),
        ),
    ]
