# Generated by Django 4.1.3 on 2022-11-28 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wineceller", "0002_remove_wineceller_wine_wineceller_wine_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wineceller",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winecellers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
