# Generated by Django 4.1.3 on 2022-11-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wineceller", "0003_alter_wine_wine_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wine", old_name="country", new_name="kr_country",
        ),
        migrations.RenameField(
            model_name="wine", old_name="grape_list", new_name="kr_grape_list",
        ),
        migrations.RenameField(
            model_name="wine", old_name="region", new_name="kr_region",
        ),
    ]
