# Generated by Django 4.1.3 on 2022-11-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wineceller", "0003_alter_wineceller_owner"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wine",
        ),
    ]
