# Generated by Django 4.1.3 on 2022-11-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wineceller", "0004_rename_country_wine_kr_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="have_tried",
            field=models.BooleanField(default=False, verbose_name="먹어본 와인"),
        ),
        migrations.AddField(
            model_name="wine",
            name="is_liked",
            field=models.BooleanField(default=False, verbose_name="찜한 와인"),
        ),
        migrations.AlterField(
            model_name="wine",
            name="acidic",
            field=models.PositiveIntegerField(verbose_name="산도"),
        ),
        migrations.AlterField(
            model_name="wine",
            name="body",
            field=models.PositiveIntegerField(verbose_name="바디감"),
        ),
        migrations.AlterField(
            model_name="wine",
            name="sweet",
            field=models.PositiveIntegerField(verbose_name="당도"),
        ),
        migrations.AlterField(
            model_name="wine",
            name="tannic",
            field=models.PositiveIntegerField(verbose_name="타닌감"),
        ),
    ]
