# Generated by Django 4.1.3 on 2022-11-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wineceller", "0005_wine_have_tried_wine_is_liked_alter_wine_acidic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="food_list",
            field=models.CharField(max_length=500, verbose_name="푸드 페어링 리스트"),
        ),
        migrations.AlterField(
            model_name="wine",
            name="kr_grape_list",
            field=models.CharField(max_length=500, verbose_name="품종리스트"),
        ),
        migrations.AlterField(
            model_name="wine",
            name="notes_list",
            field=models.CharField(max_length=500, verbose_name="향 리스트"),
        ),
    ]
