# Generated by Django 4.1.3 on 2022-11-16 08:16

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wineceller", "0006_alter_wine_food_list_alter_wine_kr_grape_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="acidic",
            field=models.IntegerField(verbose_name="산도"),
        ),
        migrations.AlterField(
            model_name="wine",
            name="body",
            field=models.IntegerField(verbose_name="바디감"),
        ),
        migrations.AlterField(
            model_name="wine",
            name="food_list",
            field=djongo.models.fields.JSONField(verbose_name="푸드 페어링 리스트"),
        ),
        migrations.AlterField(
            model_name="wine",
            name="kr_grape_list",
            field=djongo.models.fields.JSONField(verbose_name="품종리스트"),
        ),
        migrations.AlterField(
            model_name="wine",
            name="notes_list",
            field=djongo.models.fields.JSONField(verbose_name="향 리스트"),
        ),
        migrations.AlterField(
            model_name="wine",
            name="sweet",
            field=models.IntegerField(verbose_name="당도"),
        ),
        migrations.AlterField(
            model_name="wine",
            name="tannic",
            field=models.IntegerField(verbose_name="타닌감"),
        ),
    ]
