# Generated by Django 4.1.3 on 2022-11-16 08:18

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wineceller", "0007_alter_wine_acidic_alter_wine_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="food_list",
            field=djongo.models.fields.JSONField(null=True, verbose_name="푸드 페어링 리스트"),
        ),
        migrations.AlterField(
            model_name="wine",
            name="kr_grape_list",
            field=djongo.models.fields.JSONField(null=True, verbose_name="품종리스트"),
        ),
        migrations.AlterField(
            model_name="wine",
            name="notes_list",
            field=djongo.models.fields.JSONField(null=True, verbose_name="향 리스트"),
        ),
    ]
