# Generated by Django 4.1.2 on 2022-11-16 09:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wineceller", "0011_alter_wine_food_list_alter_wine_kr_grape_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="food_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                default=[],
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="kr_grape_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                default=[],
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="notes_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                default=[],
                size=None,
            ),
        ),
    ]
