# Generated by Django 4.1.3 on 2022-11-27 11:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_review_wine_review_wine_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='hashtag',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
        migrations.AddField(
            model_name='review',
            name='hashtag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None),
        ),
    ]
