# Generated by Django 4.1.3 on 2022-11-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_remove_review_hashtag_delete_hashtag_review_hashtag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="wine_id",
            field=models.IntegerField(default=0),
        ),
    ]
