# Generated by Django 4.1.3 on 2022-11-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("wine_picture", models.ImageField(upload_to="")),
                ("kname", models.CharField(max_length=100, verbose_name="와인명")),
                ("ename", models.CharField(max_length=100, verbose_name="winename")),
                ("winetype", models.CharField(max_length=10, verbose_name="winetype")),
                ("description", models.TextField(verbose_name="와인상세정보")),
            ],
            options={"abstract": False,},
        ),
    ]
