# Generated by Django 4.1.3 on 2022-11-21 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("winesearch", "0002_alter_winesearch_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="winesearch",
            name="searched_at",
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
